[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts/src/v0.8',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@foundry-devops/=lib/foundry-devops/src',
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
]
solc = '0.8.19'

[etherscan]
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
