import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from '@/components/EthWallet'
import "./globals.css";
import AntdStyleRegistry from "@/components/AntdStyledComponentsRegistry";

import Dashborad from "@/components/Dashborad";
import "@rainbow-me/rainbowkit/styles.css";
import Home from "@/components/Home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <AntdStyleRegistry>
          <Dashborad />
          <Home>{children}</Home>
        </AntdStyleRegistry>
        </Providers>
      </body>
    </html>
  );
}
